In [12]:
import numpy as np
import pandas as pd

In [13]:
a=[1,2,3,4,5]

In [14]:
s= pd.Series(a)

In [15]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [16]:

d={"sukhman":97,"amrit":98,"kush":100}
s=pd.Series(d )

In [17]:
s

sukhman     97
amrit       98
kush       100
dtype: int64

In [18]:
df=pd.DataFrame([d])

In [19]:
df

   sukhman  amrit  kush
0       97     98   100

In [20]:
df=pd.DataFrame({ "name": ["sukhman","amrit"],
     "salary":[8000 , 6000]})

In [21]:
df

      name  salary
0  sukhman    8000
1    amrit    6000

In [22]:
dp=pd.read_csv("employees_100.csv")

In [23]:
dp

,EmployeeID,Name,Age,Department,Position,Salary,Experience,City
0,1,Pooja Gupta,58,Sales,Lead,54501,30,Pune
1,2,Sneha Gupta,36,Sales,Associate,139194,7,Pune
2,3,Reyansh Gupta,41,Operations,Associate,83987,34,Chandigarh
3,4,Sneha Singh,39,Sales,Lead,80879,27,Bengaluru
4,5,Aditya Singh,54,Sales,Manager,123421,20,Chandigarh
...,...,...,...,...,...,...,...,...
95,96,Pooja Patel,48,HR,Manager,130497,16,Chandigarh
96,97,Neha Sharma,45,Finance,Engineer,63433,17,Pune
97,98,Krishna Patel,51,Marketing,Engineer,134367,5,Pune
98,99,Vivaan Sharma,58,Operations,Lead,158963,31,Pune
99,100,Krishna Patel,52,Marketing,Analyst,120196,9,Pune

In [24]:
dp.head()

,EmployeeID,Name,Age,Department,Position,Salary,Experience,City
0,1,Pooja Gupta,58,Sales,Lead,54501,30,Pune
1,2,Sneha Gupta,36,Sales,Associate,139194,7,Pune
2,3,Reyansh Gupta,41,Operations,Associate,83987,34,Chandigarh
3,4,Sneha Singh,39,Sales,Lead,80879,27,Bengaluru
4,5,Aditya Singh,54,Sales,Manager,123421,20,Chandigarh

In [25]:
dp.tail(25)

,EmployeeID,Name,Age,Department,Position,Salary,Experience,City
75,76,Aarav Patel,21,Marketing,Intern,79800,17,Mumbai
76,77,Aarav Gupta,35,HR,Engineer,55573,6,Bengaluru
77,78,Sai Patel,45,Finance,Lead,37769,11,Lucknow
78,79,Ananya Gupta,40,HR,Engineer,65687,1,Hyderabad
79,80,Kabir Singh,22,Finance,Analyst,37172,35,Delhi
80,81,Sneha Verma,26,Sales,Engineer,168866,15,Chandigarh
81,82,Sneha Patel,24,Marketing,Manager,84981,8,Mumbai
82,83,Reyansh Gupta,23,HR,Associate,110666,29,Pune
83,84,Aisha Singh,37,Operations,Analyst,146469,16,Hyderabad
84,85,Arjun Sharma,40,Marketing,Lead,131693,23,Lucknow
85,86,Rohan Patel,23,Marketing,Analyst,159198,14,Chandigarh
86,87,Ishaan Verma,26,Sales,Intern,129520,13,Bengaluru
87,88,Ishaan Sharma,29,Marketing,Lead,55373,34,Hyderabad
88,89,Ananya Verma,49,Marketing,Manager,52265,29,Lucknow
89,90,Vihaan Gupta,55,IT,Lead,109352,9,Jaipur
90,91,Ishaan Verma,33,Marketing,Engineer,145966,35,Chandigarh
91,92,Arjun Kumar,44,Marketing,Analyst,62356,22,Bengaluru
92,93,Vihaan Verma,26,IT,Analyst,145426,35,Chandigarh
93,94,Kabir Kumar,51,Operations,Lead,150374,18,Jaipur
94,95,Kabir Singh,33,Sales,Manager,89010,18,Bengaluru
95,96,Pooja Patel,48,HR,Manager,130497,16,Chandigarh
96,97,Neha Sharma,45,Finance,Engineer,63433,17,Pune
97,98,Krishna Patel,51,Marketing,Engineer,134367,5,Pune
98,99,Vivaan Sharma,58,Operations,Lead,158963,31,Pune
99,100,Krishna Patel,52,Marketing,Analyst,120196,9,Pune

In [26]:
dp.tail()

,EmployeeID,Name,Age,Department,Position,Salary,Experience,City
95,96,Pooja Patel,48,HR,Manager,130497,16,Chandigarh
96,97,Neha Sharma,45,Finance,Engineer,63433,17,Pune
97,98,Krishna Patel,51,Marketing,Engineer,134367,5,Pune
98,99,Vivaan Sharma,58,Operations,Lead,158963,31,Pune
99,100,Krishna Patel,52,Marketing,Analyst,120196,9,Pune

In [27]:
dp.shape

(100, 8)

In [28]:
dp.sample(2)

,EmployeeID,Name,Age,Department,Position,Salary,Experience,City
55,56,Reyansh Gupta,49,Operations,Analyst,108879,33,Lucknow
46,47,Rohan Singh,23,Finance,Manager,33401,5,Chandigarh

In [29]:
dp.sample(10)

,EmployeeID,Name,Age,Department,Position,Salary,Experience,City
3,4,Sneha Singh,39,Sales,Lead,80879,27,Bengaluru
44,45,Ishaan Patel,60,Sales,Associate,162016,28,Jaipur
78,79,Ananya Gupta,40,HR,Engineer,65687,1,Hyderabad
56,57,Vihaan Singh,21,IT,Lead,108454,25,Hyderabad
73,74,Sai Sharma,57,Sales,Associate,120656,28,Mumbai
35,36,Kabir Gupta,21,Marketing,Associate,55476,19,Bengaluru
21,22,Karan Kumar,52,HR,Intern,67779,19,Hyderabad
82,83,Reyansh Gupta,23,HR,Associate,110666,29,Pune
92,93,Vihaan Verma,26,IT,Analyst,145426,35,Chandigarh
25,26,Ananya Gupta,42,Sales,Associate,171314,28,Pune

In [30]:
dp.dtypes

EmployeeID     int64
Name          object
Age            int64
Department    object
Position      object
Salary         int64
Experience     int64
City          object
dtype: object

In [31]:
dp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  100 non-null    int64
 1   Name        100 non-null    object
 2   Age         100 non-null    int64
 3   Department  100 non-null    object
 4   Position    100 non-null    object
 5   Salary      100 non-null    int64
 6   Experience  100 non-null    int64
 7   City        100 non-null    object
dtypes: int64(4), object(4)
memory usage: 6.4+ KB

In [32]:
dp.describe()

       EmployeeID         Age         Salary  Experience
count  100.000000  100.000000     100.000000  100.000000
mean    50.500000   40.010000  102769.770000   19.670000
std     29.011492   11.605028   41822.273681    9.766005
min      1.000000   21.000000   33401.000000    0.000000
25%     25.750000   30.750000   65556.250000   12.750000
50%     50.500000   41.000000  104282.500000   19.000000
75%     75.250000   49.000000  134948.250000   28.250000
max    100.000000   60.000000  173090.000000   35.000000

In [33]:
dp.isnull()

    EmployeeID   Name    Age  Department  Position  Salary  Experience   City
0        False  False  False       False     False   False       False  False
1        False  False  False       False     False   False       False  False
2        False  False  False       False     False   False       False  False
3        False  False  False       False     False   False       False  False
4        False  False  False       False     False   False       False  False
..         ...    ...    ...         ...       ...     ...         ...    ...
95       False  False  False       False     False   False       False  False
96       False  False  False       False     False   False       False  False
97       False  False  False       False     False   False       False  False
98       False  False  False       False     False   False       False  False
99       False  False  False       False     False   False       False  False

[100 rows x 8 columns]

In [34]:
dp.isnull().sum()

EmployeeID    0
Name          0
Age           0
Department    0
Position      0
Salary        0
Experience    0
City          0
dtype: int64

In [35]:
dp['EmployeeID']

0       1
1       2
2       3
3       4
4       5
     ...
95     96
96     97
97     98
98     99
99    100
Name: EmployeeID, Length: 100, dtype: int64

In [36]:
dp['Name']

0       Pooja Gupta
1       Sneha Gupta
2     Reyansh Gupta
3       Sneha Singh
4      Aditya Singh
          ...
95      Pooja Patel
96      Neha Sharma
97    Krishna Patel
98    Vivaan Sharma
99    Krishna Patel
Name: Name, Length: 100, dtype: object

In [37]:
#to access two columns together
dp[['Age','Salary']]

    Age  Salary
0    58   54501
1    36  139194
2    41   83987
3    39   80879
4    54  123421
..  ...     ...
95   48  130497
96   45   63433
97   51  134367
98   58  158963
99   52  120196

[100 rows x 2 columns]

In [38]:
# performing function on two columns selected
dp[['Age','Salary']].head(15)

    Age  Salary
0    58   54501
1    36  139194
2    41   83987
3    39   80879
4    54  123421
5    30  125944
6    31  162465
7    39   97636
8    51   57636
9    28  103496
10   23  133294
11   53  167980
12   21   85032
13   42   57966
14   59  127531

In [39]:
dp=dp.set_index("EmployeeID")

In [40]:
dp

,Name,Age,Department,Position,Salary,Experience,City
EmployeeID,,,,,,,
1,Pooja Gupta,58,Sales,Lead,54501,30,Pune
2,Sneha Gupta,36,Sales,Associate,139194,7,Pune
3,Reyansh Gupta,41,Operations,Associate,83987,34,Chandigarh
4,Sneha Singh,39,Sales,Lead,80879,27,Bengaluru
5,Aditya Singh,54,Sales,Manager,123421,20,Chandigarh
...,...,...,...,...,...,...,...
96,Pooja Patel,48,HR,Manager,130497,16,Chandigarh
97,Neha Sharma,45,Finance,Engineer,63433,17,Pune
98,Krishna Patel,51,Marketing,Engineer,134367,5,Pune
99,Vivaan Sharma,58,Operations,Lead,158963,31,Pune
100,Krishna Patel,52,Marketing,Analyst,120196,9,Pune

In [41]:
dp.loc[1]

Name          Pooja Gupta
Age                    58
Department          Sales
Position             Lead
Salary              54501
Experience             30
City                 Pune
Name: 1, dtype: object

In [42]:
dp.loc[45:49:2]

,Name,Age,Department,Position,Salary,Experience,City
EmployeeID,,,,,,,
45,Ishaan Patel,60,Sales,Associate,162016,28,Jaipur
47,Rohan Singh,23,Finance,Manager,33401,5,Chandigarh
49,Vihaan Gupta,27,Finance,Intern,37019,23,Bengaluru

In [43]:
dp.iloc[0:10]

,Name,Age,Department,Position,Salary,Experience,City
EmployeeID,,,,,,,
1,Pooja Gupta,58,Sales,Lead,54501,30,Pune
2,Sneha Gupta,36,Sales,Associate,139194,7,Pune
3,Reyansh Gupta,41,Operations,Associate,83987,34,Chandigarh
4,Sneha Singh,39,Sales,Lead,80879,27,Bengaluru
5,Aditya Singh,54,Sales,Manager,123421,20,Chandigarh
6,Rohan Patel,30,Operations,Intern,125944,23,Jaipur
7,Ishaan Patel,31,IT,Engineer,162465,1,Lucknow
8,Rahul Verma,39,HR,Lead,97636,9,Hyderabad
9,Rahul Gupta,51,Marketing,Lead,57636,17,Mumbai
10,Aisha Kumar,28,Finance,Analyst,103496,20,Pune

In [44]:
dp.loc[51:61]["Salary"]

EmployeeID
51     66885
52    156570
53    154284
54     67268
55     46986
56    108879
57    108454
58    111002
59     39844
60     83962
61     79938
Name: Salary, dtype: int64

In [45]:
dp.loc[51:61][["Salary" , "Age"]]

            Salary  Age
EmployeeID
51           66885   48
52          156570   44
53          154284   49
54           67268   58
55           46986   58
56          108879   49
57          108454   21
58          111002   39
59           39844   33
60           83962   36
61           79938   54

In [46]:
dp.iloc[1:14:2][["Age" , "Salary"]]

            Age  Salary
EmployeeID
2            36  139194
4            39   80879
6            30  125944
8            39   97636
10           28  103496
12           53  167980
14           42   57966

In [47]:
dp['Salary'] >90000

EmployeeID
1      False
2       True
3      False
4      False
5       True
       ...
96      True
97     False
98      True
99      True
100     True
Name: Salary, Length: 100, dtype: bool

In [48]:
dp[dp['Salary'] >90000]

,Name,Age,Department,Position,Salary,Experience,City
EmployeeID,,,,,,,
2,Sneha Gupta,36,Sales,Associate,139194,7,Pune
5,Aditya Singh,54,Sales,Manager,123421,20,Chandigarh
6,Rohan Patel,30,Operations,Intern,125944,23,Jaipur
7,Ishaan Patel,31,IT,Engineer,162465,1,Lucknow
8,Rahul Verma,39,HR,Lead,97636,9,Hyderabad
10,Aisha Kumar,28,Finance,Analyst,103496,20,Pune
11,Vivaan Kumar,23,Sales,Associate,133294,6,Mumbai
12,Reyansh Patel,53,Operations,Analyst,167980,27,Chandigarh
15,Rohan Patel,59,Finance,Lead,127531,27,Hyderabad
16,Reyansh Singh,29,Finance,Engineer,171095,26,Pune
18,Sai Singh,32,Operations,Associate,169180,19,Pune
19,Reyansh Patel,32,HR,Intern,104904,31,Lucknow
20,Aisha Gupta,22,Sales,Intern,108582,29,Chandigarh
21,Krishna Sharma,22,IT,Lead,102533,13,Pune
23,Arjun Singh,41,Finance,Engineer,103661,5,Bengaluru
26,Ananya Gupta,42,Sales,Associate,171314,28,Pune
27,Reyansh Patel,47,Operations,Manager,116551,34,Mumbai
28,Aarav Gupta,52,IT,Engineer,146274,8,Pune
30,Aarav Sharma,47,HR,Lead,113544,35,Mumbai
33,Aarav Sharma,57,Finance,Associate,110803,10,Mumbai
35,Sai Verma,43,Finance,Intern,156347,23,Delhi
37,Ishaan Gupta,46,Operations,Intern,90843,22,Hyderabad
38,Ananya Verma,43,Sales,Lead,134832,28,Pune
39,Ishaan Verma,46,Finance,Lead,145648,30,Pune
40,Ishaan Patel,46,Finance,Intern,120133,29,Chandigarh
41,Pooja Gupta,28,Sales,Analyst,103451,0,Jaipur
43,Priya Singh,24,Sales,Manager,132662,8,Jaipur
44,Reyansh Kumar,34,Operations,Engineer,135297,13,Mumbai
45,Ishaan Patel,60,Sales,Associate,162016,28,Jaipur
50,Aditya Patel,36,IT,Associate,112891,15,Delhi
52,Ananya Verma,44,IT,Associate,156570,11,Chandigarh
53,Rahul Verma,49,Marketing,Manager,154284,10,Bengaluru
56,Reyansh Gupta,49,Operations,Analyst,108879,33,Lucknow
57,Vihaan Singh,21,IT,Lead,108454,25,Hyderabad
58,Ishaan Patel,39,Sales,Associate,111002,18,Bengaluru
63,Neha Singh,26,Finance,Manager,127882,28,Delhi
65,Ishaan Sharma,37,Marketing,Manager,99800,33,Mumbai
66,Priya Sharma,52,HR,Associate,161181,3,Mumbai
67,Reyansh Kumar,33,Sales,Manager,100788,15,Delhi
68,Pooja Patel,58,Operations,Analyst,173090,2,Mumbai
71,Aarav Gupta,23,IT,Associate,140907,35,Mumbai
72,Reyansh Singh,58,IT,Lead,160608,27,Lucknow
73,Rahul Gupta,47,Finance,Lead,167756,12,Lucknow
74,Sai Sharma,57,Sales,Associate,120656,28,Mumbai
81,Sneha Verma,26,Sales,Engineer,168866,15,Chandigarh
83,Reyansh Gupta,23,HR,Associate,110666,29,Pune
84,Aisha Singh,37,Operations,Analyst,146469,16,Hyderabad
85,Arjun Sharma,40,Marketing,Lead,131693,23,Lucknow
86,Rohan Patel,23,Marketing,Analyst,159198,14,Chandigarh
87,Ishaan Verma,26,Sales,Intern,129520,13,Bengaluru
90,Vihaan Gupta,55,IT,Lead,109352,9,Jaipur
91,Ishaan Verma,33,Marketing,Engineer,145966,35,Chandigarh
93,Vihaan Verma,26,IT,Analyst,145426,35,Chandigarh
94,Kabir Kumar,51,Operations,Lead,150374,18,Jaipur
96,Pooja Patel,48,HR,Manager,130497,16,Chandigarh
98,Krishna Patel,51,Marketing,Engineer,134367,5,Pune
99,Vivaan Sharma,58,Operations,Lead,158963,31,Pune
100,Krishna Patel,52,Marketing,Analyst,120196,9,Pune

In [49]:
dp['Department']=="Sales"

EmployeeID
1       True
2       True
3      False
4       True
5       True
       ...
96     False
97     False
98     False
99     False
100    False
Name: Department, Length: 100, dtype: bool

In [50]:
dp[(dp['Department']=="Sales") & (dp["Age"]>=30)]

,Name,Age,Department,Position,Salary,Experience,City
EmployeeID,,,,,,,
1,Pooja Gupta,58,Sales,Lead,54501,30,Pune
2,Sneha Gupta,36,Sales,Associate,139194,7,Pune
4,Sneha Singh,39,Sales,Lead,80879,27,Bengaluru
5,Aditya Singh,54,Sales,Manager,123421,20,Chandigarh
17,Arjun Sharma,37,Sales,Manager,77002,30,Delhi
25,Pooja Verma,55,Sales,Associate,65164,14,Hyderabad
26,Ananya Gupta,42,Sales,Associate,171314,28,Pune
38,Ananya Verma,43,Sales,Lead,134832,28,Pune
45,Ishaan Patel,60,Sales,Associate,162016,28,Jaipur
58,Ishaan Patel,39,Sales,Associate,111002,18,Bengaluru
67,Reyansh Kumar,33,Sales,Manager,100788,15,Delhi
69,Kabir Patel,59,Sales,Lead,76344,15,Hyderabad
74,Sai Sharma,57,Sales,Associate,120656,28,Mumbai
95,Kabir Singh,33,Sales,Manager,89010,18,Bengaluru

In [51]:
dp[(dp['Department']=="Sales") & (dp["Age"]>=30) & (dp["Salary"]>=100000)]

,Name,Age,Department,Position,Salary,Experience,City
EmployeeID,,,,,,,
2,Sneha Gupta,36,Sales,Associate,139194,7,Pune
5,Aditya Singh,54,Sales,Manager,123421,20,Chandigarh
26,Ananya Gupta,42,Sales,Associate,171314,28,Pune
38,Ananya Verma,43,Sales,Lead,134832,28,Pune
45,Ishaan Patel,60,Sales,Associate,162016,28,Jaipur
58,Ishaan Patel,39,Sales,Associate,111002,18,Bengaluru
67,Reyansh Kumar,33,Sales,Manager,100788,15,Delhi
74,Sai Sharma,57,Sales,Associate,120656,28,Mumbai

In [52]:
dp[dp['Department'].isin(["IT","HR"])]

,Name,Age,Department,Position,Salary,Experience,City
EmployeeID,,,,,,,
7,Ishaan Patel,31,IT,Engineer,162465,1,Lucknow
8,Rahul Verma,39,HR,Lead,97636,9,Hyderabad
13,Karan Singh,21,IT,Lead,85032,33,Pune
14,Aisha Singh,42,IT,Manager,57966,19,Hyderabad
19,Reyansh Patel,32,HR,Intern,104904,31,Lucknow
21,Krishna Sharma,22,IT,Lead,102533,13,Pune
22,Karan Kumar,52,HR,Intern,67779,19,Hyderabad
28,Aarav Gupta,52,IT,Engineer,146274,8,Pune
29,Reyansh Kumar,41,HR,Associate,39346,7,Mumbai
30,Aarav Sharma,47,HR,Lead,113544,35,Mumbai
31,Neha Sharma,42,IT,Associate,63908,15,Delhi
34,Neha Singh,44,IT,Intern,37452,25,Lucknow
42,Ananya Singh,35,HR,Manager,84982,29,Mumbai
48,Vivaan Sharma,38,IT,Analyst,39484,20,Mumbai
50,Aditya Patel,36,IT,Associate,112891,15,Delhi
52,Ananya Verma,44,IT,Associate,156570,11,Chandigarh
54,Arjun Patel,58,IT,Intern,67268,29,Hyderabad
57,Vihaan Singh,21,IT,Lead,108454,25,Hyderabad
64,Krishna Sharma,29,HR,Associate,43688,29,Jaipur
66,Priya Sharma,52,HR,Associate,161181,3,Mumbai
71,Aarav Gupta,23,IT,Associate,140907,35,Mumbai
72,Reyansh Singh,58,IT,Lead,160608,27,Lucknow
77,Aarav Gupta,35,HR,Engineer,55573,6,Bengaluru
79,Ananya Gupta,40,HR,Engineer,65687,1,Hyderabad
83,Reyansh Gupta,23,HR,Associate,110666,29,Pune
90,Vihaan Gupta,55,IT,Lead,109352,9,Jaipur
93,Vihaan Verma,26,IT,Analyst,145426,35,Chandigarh
96,Pooja Patel,48,HR,Manager,130497,16,Chandigarh

In [53]:
dp[dp['Name'].str.contains("Verma")]

,Name,Age,Department,Position,Salary,Experience,City
EmployeeID,,,,,,,
8,Rahul Verma,39,HR,Lead,97636,9,Hyderabad
24,Rohan Verma,33,Finance,Engineer,33437,19,Pune
25,Pooja Verma,55,Sales,Associate,65164,14,Hyderabad
35,Sai Verma,43,Finance,Intern,156347,23,Delhi
38,Ananya Verma,43,Sales,Lead,134832,28,Pune
39,Ishaan Verma,46,Finance,Lead,145648,30,Pune
46,Neha Verma,41,Marketing,Manager,57409,17,Mumbai
52,Ananya Verma,44,IT,Associate,156570,11,Chandigarh
53,Rahul Verma,49,Marketing,Manager,154284,10,Bengaluru
81,Sneha Verma,26,Sales,Engineer,168866,15,Chandigarh
87,Ishaan Verma,26,Sales,Intern,129520,13,Bengaluru
89,Ananya Verma,49,Marketing,Manager,52265,29,Lucknow
91,Ishaan Verma,33,Marketing,Engineer,145966,35,Chandigarh
93,Vihaan Verma,26,IT,Analyst,145426,35,Chandigarh

In [54]:
dp['Department'].value_counts()

Department
Sales         20
Finance       19
Marketing     17
Operations    16
IT            16
HR            12
Name: count, dtype: int64

In [55]:
dp.isnull().sum()

Name          0
Age           0
Department    0
Position      0
Salary        0
Experience    0
City          0
dtype: int64

In [56]:
dp.duplicated().sum()

np.int64(0)

In [58]:
dp=dp.reset_index()

In [59]:
dp.duplicated(subset=["EmployeeID"]).sum()

np.int64(0)

In [60]:
dp['Salary']=pd.to_numeric(dp["Salary"])

In [62]:
dp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  100 non-null    int64
 1   Name        100 non-null    object
 2   Age         100 non-null    int64
 3   Department  100 non-null    object
 4   Position    100 non-null    object
 5   Salary      100 non-null    int64
 6   Experience  100 non-null    int64
 7   City        100 non-null    object
dtypes: int64(4), object(4)
memory usage: 6.4+ KB

In [63]:
dp["Salary"].median()

104282.5

In [64]:
dp["Salary"].std()

41822.27368108598

In [65]:
dp["Salary"].var()

1749102575.8556569

In [66]:
dp.rename(columns={"EmployeeID" : "empID"}, inplace=True)

In [67]:
dp.head()

,empID,Name,Age,Department,Position,Salary,Experience,City
0,1,Pooja Gupta,58,Sales,Lead,54501,30,Pune
1,2,Sneha Gupta,36,Sales,Associate,139194,7,Pune
2,3,Reyansh Gupta,41,Operations,Associate,83987,34,Chandigarh
3,4,Sneha Singh,39,Sales,Lead,80879,27,Bengaluru
4,5,Aditya Singh,54,Sales,Manager,123421,20,Chandigarh

In [68]:
dp["annual_salary"]=dp["Salary"]*12

In [69]:
dp

,empID,Name,Age,Department,Position,Salary,Experience,City,annual_salary
0,1,Pooja Gupta,58,Sales,Lead,54501,30,Pune,654012
1,2,Sneha Gupta,36,Sales,Associate,139194,7,Pune,1670328
2,3,Reyansh Gupta,41,Operations,Associate,83987,34,Chandigarh,1007844
3,4,Sneha Singh,39,Sales,Lead,80879,27,Bengaluru,970548
4,5,Aditya Singh,54,Sales,Manager,123421,20,Chandigarh,1481052
...,...,...,...,...,...,...,...,...,...
95,96,Pooja Patel,48,HR,Manager,130497,16,Chandigarh,1565964
96,97,Neha Sharma,45,Finance,Engineer,63433,17,Pune,761196
97,98,Krishna Patel,51,Marketing,Engineer,134367,5,Pune,1612404
98,99,Vivaan Sharma,58,Operations,Lead,158963,31,Pune,1907556
99,100,Krishna Patel,52,Marketing,Analyst,120196,9,Pune,1442352

In [87]:
def categorize(num):
  if num >= 10 :
    return "Experienced"
  elif num <=10 :
     return "Learner"

In [88]:
dp['Experience_Status']=dp['Experience'].apply(categorize)

In [89]:
dp

,empID,Name,Age,Department,Position,Salary,Experience,City,annual_salary,Experience_Status
0,1,Pooja Gupta,58,Sales,Lead,54501,30,Pune,654012,Experienced
1,2,Sneha Gupta,36,Sales,Associate,139194,7,Pune,1670328,Learner
2,3,Reyansh Gupta,41,Operations,Associate,83987,34,Chandigarh,1007844,Experienced
3,4,Sneha Singh,39,Sales,Lead,80879,27,Bengaluru,970548,Experienced
4,5,Aditya Singh,54,Sales,Manager,123421,20,Chandigarh,1481052,Experienced
...,...,...,...,...,...,...,...,...,...,...
95,96,Pooja Patel,48,HR,Manager,130497,16,Chandigarh,1565964,Experienced
96,97,Neha Sharma,45,Finance,Engineer,63433,17,Pune,761196,Experienced
97,98,Krishna Patel,51,Marketing,Engineer,134367,5,Pune,1612404,Learner
98,99,Vivaan Sharma,58,Operations,Lead,158963,31,Pune,1907556,Experienced
99,100,Krishna Patel,52,Marketing,Analyst,120196,9,Pune,1442352,Learner

In [92]:
department_codes={"Marketing":"MKT", "Finance":"FIN","Operations":"OPs","Sales":"Sa"}
dp["Department_code"]=dp["Department"].map(department_codes)

In [93]:
dp

,empID,Name,Age,Department,Position,Salary,Experience,City,annual_salary,Experience_Status,Department_code
0,1,Pooja Gupta,58,Sales,Lead,54501,30,Pune,654012,Experienced,Sa
1,2,Sneha Gupta,36,Sales,Associate,139194,7,Pune,1670328,Learner,Sa
2,3,Reyansh Gupta,41,Operations,Associate,83987,34,Chandigarh,1007844,Experienced,OPs
3,4,Sneha Singh,39,Sales,Lead,80879,27,Bengaluru,970548,Experienced,Sa
4,5,Aditya Singh,54,Sales,Manager,123421,20,Chandigarh,1481052,Experienced,Sa
...,...,...,...,...,...,...,...,...,...,...,...
95,96,Pooja Patel,48,HR,Manager,130497,16,Chandigarh,1565964,Experienced,NaN
96,97,Neha Sharma,45,Finance,Engineer,63433,17,Pune,761196,Experienced,FIN
97,98,Krishna Patel,51,Marketing,Engineer,134367,5,Pune,1612404,Learner,MKT
98,99,Vivaan Sharma,58,Operations,Lead,158963,31,Pune,1907556,Experienced,OPs
99,100,Krishna Patel,52,Marketing,Analyst,120196,9,Pune,1442352,Learner,MKT

In [95]:
dp.sort_values(by="Age")

,empID,Name,Age,Department,Position,Salary,Experience,City,annual_salary,Experience_Status,Department_code
12,13,Karan Singh,21,IT,Lead,85032,33,Pune,1020384,Experienced,NaN
35,36,Kabir Gupta,21,Marketing,Associate,55476,19,Bengaluru,665712,Experienced,MKT
56,57,Vihaan Singh,21,IT,Lead,108454,25,Hyderabad,1301448,Experienced,NaN
75,76,Aarav Patel,21,Marketing,Intern,79800,17,Mumbai,957600,Experienced,MKT
20,21,Krishna Sharma,22,IT,Lead,102533,13,Pune,1230396,Experienced,NaN
...,...,...,...,...,...,...,...,...,...,...,...
53,54,Arjun Patel,58,IT,Intern,67268,29,Hyderabad,807216,Experienced,NaN
98,99,Vivaan Sharma,58,Operations,Lead,158963,31,Pune,1907556,Experienced,OPs
14,15,Rohan Patel,59,Finance,Lead,127531,27,Hyderabad,1530372,Experienced,FIN
68,69,Kabir Patel,59,Sales,Lead,76344,15,Hyderabad,916128,Experienced,Sa
44,45,Ishaan Patel,60,Sales,Associate,162016,28,Jaipur,1944192,Experienced,Sa

In [96]:
dp.sort_values(by="Age", ascending=False)

,empID,Name,Age,Department,Position,Salary,Experience,City,annual_salary,Experience_Status,Department_code
44,45,Ishaan Patel,60,Sales,Associate,162016,28,Jaipur,1944192,Experienced,Sa
14,15,Rohan Patel,59,Finance,Lead,127531,27,Hyderabad,1530372,Experienced,FIN
68,69,Kabir Patel,59,Sales,Lead,76344,15,Hyderabad,916128,Experienced,Sa
0,1,Pooja Gupta,58,Sales,Lead,54501,30,Pune,654012,Experienced,Sa
67,68,Pooja Patel,58,Operations,Analyst,173090,2,Mumbai,2077080,Learner,OPs
...,...,...,...,...,...,...,...,...,...,...,...
20,21,Krishna Sharma,22,IT,Lead,102533,13,Pune,1230396,Experienced,NaN
35,36,Kabir Gupta,21,Marketing,Associate,55476,19,Bengaluru,665712,Experienced,MKT
12,13,Karan Singh,21,IT,Lead,85032,33,Pune,1020384,Experienced,NaN
56,57,Vihaan Singh,21,IT,Lead,108454,25,Hyderabad,1301448,Experienced,NaN
75,76,Aarav Patel,21,Marketing,Intern,79800,17,Mumbai,957600,Experienced,MKT

In [99]:
dp["Salary_rank"]=dp["Salary"].rank(ascending=False)

In [100]:
dp.sort_values(by="Salary_rank")

,empID,Name,Age,Department,Position,Salary,Experience,City,annual_salary,Experience_Status,Department_code,Salary_rank
67,68,Pooja Patel,58,Operations,Analyst,173090,2,Mumbai,2077080,Learner,OPs,1.0
25,26,Ananya Gupta,42,Sales,Associate,171314,28,Pune,2055768,Experienced,Sa,2.0
15,16,Reyansh Singh,29,Finance,Engineer,171095,26,Pune,2053140,Experienced,FIN,3.0
17,18,Sai Singh,32,Operations,Associate,169180,19,Pune,2030160,Experienced,OPs,4.0
80,81,Sneha Verma,26,Sales,Engineer,168866,15,Chandigarh,2026392,Experienced,Sa,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
33,34,Neha Singh,44,IT,Intern,37452,25,Lucknow,449424,Experienced,NaN,96.0
79,80,Kabir Singh,22,Finance,Analyst,37172,35,Delhi,446064,Experienced,FIN,97.0
48,49,Vihaan Gupta,27,Finance,Intern,37019,23,Bengaluru,444228,Experienced,FIN,98.0
23,24,Rohan Verma,33,Finance,Engineer,33437,19,Pune,401244,Experienced,FIN,99.0
46,47,Rohan Singh,23,Finance,Manager,33401,5,Chandigarh,400812,Learner,FIN,100.0

In [106]:
dp.groupby("City")["Age"].mean()

City
Bengaluru     35.909091
Chandigarh    36.071429
Delhi         37.888889
Hyderabad     45.071429
Jaipur        41.888889
Lucknow       43.888889
Mumbai        40.352941
Pune          39.470588
Name: Age, dtype: float64

In [103]:
dp

,empID,Name,Age,Department,Position,Salary,Experience,City,annual_salary,Experience_Status,Department_code,Salary_rank
0,1,Pooja Gupta,58,Sales,Lead,54501,30,Pune,654012,Experienced,Sa,86.0
1,2,Sneha Gupta,36,Sales,Associate,139194,7,Pune,1670328,Learner,Sa,24.0
2,3,Reyansh Gupta,41,Operations,Associate,83987,34,Chandigarh,1007844,Experienced,OPs,64.0
3,4,Sneha Singh,39,Sales,Lead,80879,27,Bengaluru,970548,Experienced,Sa,66.0
4,5,Aditya Singh,54,Sales,Manager,123421,20,Chandigarh,1481052,Experienced,Sa,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Pooja Patel,48,HR,Manager,130497,16,Chandigarh,1565964,Experienced,NaN,31.0
96,97,Neha Sharma,45,Finance,Engineer,63433,17,Pune,761196,Experienced,FIN,78.0
97,98,Krishna Patel,51,Marketing,Engineer,134367,5,Pune,1612404,Learner,MKT,27.0
98,99,Vivaan Sharma,58,Operations,Lead,158963,31,Pune,1907556,Experienced,OPs,13.0
99,100,Krishna Patel,52,Marketing,Analyst,120196,9,Pune,1442352,Learner,MKT,38.0

In [107]:
dp.groupby("City")["Salary"].max()

City
Bengaluru     154284
Chandigarh    168866
Delhi         156347
Hyderabad     146469
Jaipur        162016
Lucknow       167756
Mumbai        173090
Pune          171314
Name: Salary, dtype: int64

In [108]:
# group by with two 2 columns
dp.groupby(["City","Department"])["Salary"].mean()

City        Department
Bengaluru   Finance        70340.000000
            HR             55573.000000
            Marketing      89912.000000
            Sales         102602.750000
Chandigarh  Finance        76767.000000
            HR            130497.000000
            IT            150998.000000
            Marketing     114740.000000
            Operations     97270.333333
            Sales         133623.000000
Delhi       Finance       100334.750000
            IT             88399.500000
            Operations     66885.000000
            Sales          88895.000000
Hyderabad   Finance        87258.500000
            HR             77034.000000
            IT             77896.000000
            Marketing      55373.000000
            Operations    107091.333333
            Sales          70754.000000
Jaipur      Finance        79616.000000
            HR             43688.000000
            IT            109352.000000
            Operations    106655.000000
            Sales         132709.666667
Lucknow     Finance       102762.500000
            HR            104904.000000
            IT            120175.000000
            Marketing      91979.000000
            Operations    108879.000000
Mumbai      Finance       110803.000000
            HR             99763.250000
            IT             90195.500000
            Marketing      75925.200000
            Operations    141646.000000
            Sales         126975.000000
Pune        Finance       103421.800000
            HR            110666.000000
            IT            111279.666667
            Marketing     127281.500000
            Operations    164071.500000
            Sales         124960.250000
Name: Salary, dtype: float64

In [110]:
dp.groupby("City")[["Salary","Experience"]].max()

            Salary  Experience
City
Bengaluru   154284          27
Chandigarh  168866          35
Delhi       156347          35
Hyderabad   146469          34
Jaipur      162016          29
Lucknow     167756          33
Mumbai      173090          35
Pune        171314          33

In [114]:
dp.groupby("Department").agg({"Salary":["mean","max"],"Age":["count"],"Experience":["mean","max"]})

                   Salary           Age Experience
                     mean     max count       mean max
Department
Finance      93848.578947  171095    19  18.736842  35
HR           89623.583333  161181    12  17.833333  35
IT          106036.875000  162465    16  20.000000  35
Marketing    92787.529412  159198    17  20.117647  35
Operations  116368.437500  173090    16  22.375000  34
Sales       114124.900000  171314    20  18.850000  30

In [115]:
department_summary = dp.groupby("Department").agg({"Salary":["mean","max"],"Age":["count"],"Experience":["mean","max"]})

In [116]:
department_summary

                   Salary           Age Experience
                     mean     max count       mean max
Department
Finance      93848.578947  171095    19  18.736842  35
HR           89623.583333  161181    12  17.833333  35
IT          106036.875000  162465    16  20.000000  35
Marketing    92787.529412  159198    17  20.117647  35
Operations  116368.437500  173090    16  22.375000  34
Sales       114124.900000  171314    20  18.850000  30

In [ ]:
# From here is a more intense practise on A big healthcare datasets

In [117]:
#Load healthcare_dataset.csv into a DataFrame called df
df=pd.read_csv("healthcare_dataset.csv")

In [127]:
#print the shape (rows, columns).
df.shape

(55500, 15)

In [125]:
#Display the first 5 rows
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [121]:
#Check the data type of every column using .dtypes
df.dtypes

Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

In [122]:
df.isnull()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55499,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [123]:
#Check the data type of every column using .dtypes, and count how many missing values
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [124]:
#Find how many unique values are in the Medical Condition column, and print out what those unique values actually are.
df.nunique()

Name                  49992
Age                      77
Gender                    2
Blood Type                8
Medical Condition         6
Date of Admission      1827
Doctor                40341
Hospital              39876
Insurance Provider        5
Billing Amount        50000
Room Number             400
Admission Type            3
Discharge Date         1856
Medication                5
Test Results              3
dtype: int64

In [129]:
#Create a new DataFrame called patients that contains only these columns: Name, Age, Medical Condition, and Billing Amount.
patients=df[["Name","Age","Medical Condition","Billing Amount"]]

In [130]:
patients

                    Name  Age Medical Condition  Billing Amount
0          Bobby JacksOn   30            Cancer    18856.281306
1           LesLie TErRy   62           Obesity    33643.327287
2            DaNnY sMitH   76           Obesity    27955.096079
3           andrEw waTtS   28          Diabetes    37909.782410
4          adrIENNE bEll   43            Cancer    14238.317814
...                  ...  ...               ...             ...
55495  eLIZABeTH jaCkSOn   42            Asthma     2650.714952
55496         KYle pEREz   61           Obesity    31457.797307
55497       HEATher WaNG   38      Hypertension    27620.764717
55498     JENniFER JOneS   43         Arthritis    32451.092358
55499       jAMES GARCiA   53         Arthritis     4010.134172

[55500 rows x 4 columns]

In [137]:
#Filter the dataset to show only patients where Medical Condition is "Diabetes" and Age is greater than 50.
df[(df["Medical Condition"]=="Diabetes" )& (df["Age"] > 50)]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
12,connOR HANsEn,75,Female,A+,Diabetes,2019-12-12,Kenneth Fletcher,"Powers Miller, and Flores",Cigna,43282.283358,134,Emergency,2019-12-28,Penicillin,Abnormal
38,NIcOlE LUcErO,70,Female,O-,Diabetes,2022-03-12,Christine Johnson,"and Garcia Morris Cunningham,",Cigna,48290.693407,113,Emergency,2022-03-29,Lipitor,Abnormal
47,CHRis fRYe,58,Male,A-,Diabetes,2020-05-04,Heather Smith,Nelson-Phillips,Cigna,36992.273688,413,Urgent,2020-05-13,Aspirin,Normal
66,ChRiStOPhER gOnzAlez,59,Male,B+,Diabetes,2019-11-21,Patricia Dunn,Rhodes-Carey,Medicare,10107.187651,368,Emergency,2019-12-08,Penicillin,Abnormal
82,SeaN jenniNGs,80,Female,AB-,Diabetes,2023-11-12,James Tucker,Clark-Johnson,Blue Cross,20257.544283,255,Elective,2023-12-12,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55409,WEslEY BarkEr,58,Male,O+,Diabetes,2020-06-22,Jonathan Cabrera,Long LLC,Cigna,44241.630103,324,Urgent,2020-07-05,Ibuprofen,Normal
55416,GrEG Bush,67,Male,B-,Diabetes,2021-09-26,Joshua Davis,Ltd Cox,Cigna,16097.163523,483,Emergency,2021-10-12,Paracetamol,Abnormal
55420,SteVeN knoX,52,Female,A-,Diabetes,2023-08-12,Alicia Garcia,Molina-Phelps,UnitedHealthcare,5271.154491,379,Elective,2023-08-24,Ibuprofen,Inconclusive
55433,RonALd OBRIeN jr.,72,Female,B+,Diabetes,2019-11-16,John Singh,"Hunter and Mckenzie, Parsons",Aetna,13959.491185,462,Urgent,2019-12-06,Lipitor,Abnormal
55439,cHRiStINE MCCARty,75,Male,AB+,Diabetes,2024-04-28,Gregory Pineda,Wu-Stark,Aetna,23720.022368,313,Emergency,2024-05-19,Penicillin,Abnormal

In [138]:
#This dataset has some issues hiding in it:

# Remove exact duplicate rows using drop_duplicates().
# Some rows have a negative Billing Amount, which doesn't make sense for a hospital bill. Remove any rows where Billing Amount is less than 0.
# Print the number of rows before and after, so you can see how many were removed.

df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
55495    False
55496    False
55497    False
55498    False
55499    False
Length: 55500, dtype: bool

In [183]:

# Some rows have a negative Billing Amount, which doesn't make sense for a hospital bill. Remove any rows where Billing Amount is less than 0.
df=df[df["Billing Amount"]>=0]

In [184]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay,Age_Group,High_Bill
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2 days,Adult,LOW
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6 days,Senior,HIGH
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15 days,Senior,HIGH
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30 days,Adult,HIGH
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20 days,Adult,LOW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal,30 days,Adult,LOW
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal,9 days,Senior,HIGH
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal,28 days,Adult,HIGH
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal,6 days,Adult,HIGH
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal,27 days,Adult,LOW

In [155]:
# Print the number of rows before and after, so you can see how many were removed.
df.shape

(55500, 15)

In [162]:
#Look closely at the Name column — the capitalization is inconsistent (e.g. "Bobby JacksOn", "LesLie TErRy"). Clean it so every name is properly title-cased (e.g. "Bobby Jackson")#
df['Name'].str.title()

0            Bobby Jackson
1             Leslie Terry
2              Danny Smith
3             Andrew Watts
4            Adrienne Bell
               ...
55495    Elizabeth Jackson
55496           Kyle Perez
55497         Heather Wang
55498       Jennifer Jones
55499         James Garcia
Name: Name, Length: 55392, dtype: object

In [163]:
#Convert Date of Admission and Discharge Date into real datetime columns
df["Date of Admission"]=pd.to_datetime(df["Date of Admission"])
df["Discharge Date"]=pd.to_datetime(df["Discharge Date"])

In [165]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55392 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55392 non-null  object
 1   Age                 55392 non-null  int64
 2   Gender              55392 non-null  object
 3   Blood Type          55392 non-null  object
 4   Medical Condition   55392 non-null  object
 5   Date of Admission   55392 non-null  datetime64[ns]
 6   Doctor              55392 non-null  object
 7   Hospital            55392 non-null  object
 8   Insurance Provider  55392 non-null  object
 9   Billing Amount      55392 non-null  float64
 10  Room Number         55392 non-null  int64
 11  Admission Type      55392 non-null  object
 12  Discharge Date      55392 non-null  datetime64[ns]
 13  Medication          55392 non-null  object
 14  Test Results        55392 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(2), object(10)
memory usage: 6.8+ MB

In [166]:
#Then create a new column called Length of Stay that stores the number of days between admission and discharge for each patient.
df["Length of Stay"]=df["Discharge Date"]-df["Date of Admission"]

In [167]:
df['Length of Stay']

0        2 days
1        6 days
2       15 days
3       30 days
4       20 days
          ...
55495   30 days
55496    9 days
55497   28 days
55498    6 days
55499   27 days
Name: Length of Stay, Length: 55392, dtype: timedelta64[ns]

In [170]:
#Write a function called get_age_group(age) that returns:

# "Child" if age is 12 or under
# "Teen" if age is between 13 and 19
# "Adult" if age is between 20 and 59
# "Senior" if age is 60 or above

def get_age_group(age):
  if age <=12 :
    return "Child"
  elif 13 <= age <= 19:
    return "Teen"
  elif 20 <= age <= 59:
    return "Adult"
  else:
    return "Senior"

In [171]:
#Then use .apply() to create a new column Age Group in df using this function.
df["Age_Group"]=df["Age"].apply(get_age_group)

In [172]:
df["Age_Group"]

0         Adult
1        Senior
2        Senior
3         Adult
4         Adult
          ...
55495     Adult
55496    Senior
55497     Adult
55498     Adult
55499     Adult
Name: Age_Group, Length: 55392, dtype: object

In [176]:
#Using .apply() with a lambda function, create a new column called High Bill that stores "Yes" if a patient's Billing Amount is above the average billing amount of the whole dataset, and "No" otherwise.


df["High_Bill"]= df["Billing Amount"].apply(lambda  x: "HIGH" if x > df['Billing Amount'].mean() else "LOW ")

In [177]:
df["High_Bill"]

0        LOW
1        HIGH
2        HIGH
3        HIGH
4        LOW
         ...
55495    LOW
55496    HIGH
55497    HIGH
55498    HIGH
55499    LOW
Name: High_Bill, Length: 55392, dtype: object

In [181]:
#Sort the dataset by Billing Amount in descending order, and display the top 10 most expensive cases  just the Name, Medical Condition, and Billing Amount columns.
df.sort_values(by="Billing Amount" , ascending=False).head(10) [["Name","Medical Condition","Billing Amount"]]

                   Name Medical Condition  Billing Amount
36349     tOdd CARrILlO      Hypertension    52764.276736
51313       kARen klInE            Cancer    52373.032374
34613       kARen klInE            Cancer    52373.032374
5735     DAVId SanDOvaL      Hypertension    52271.663747
7088   kathRYN GoNzales          Diabetes    52211.852966
1574     BRETT mARshAll            Asthma    52181.837792
52826       LAuRie hOod         Arthritis    52170.036854
6663        LAuRie hOod         Arthritis    52170.036854
33117      JUstIn CLark            Cancer    52154.237722
34368      sCotT pOWElL            Cancer    52102.240889

In [182]:
#Group the data by Medical Condition and find the average Billing Amount and the average Length of Stay (from Question 8) for each condition.
df.groupby("Medical Condition")[["Billing Amount","Length of Stay"]].mean()

                   Billing Amount             Length of Stay
Medical Condition
Arthritis            25528.123850 15 days 12:24:23.697967086
Asthma               25686.666418 15 days 16:41:25.087814988
Cancer               25214.907067 15 days 12:06:43.475238922
Diabetes             25694.503197 15 days 10:07:51.520896165
Hypertension         25556.094106 15 days 11:00:40.589765828
Obesity              25860.321911 15 days 10:57:00.234476769